const APPLICATION_NAME = 'ClickARBUZBot';
const MAX_ENERGY_TO_CLICK = 100;
const MIN_ENERGY_TO_CLICK = 50;
const DEFAULT_DELAYS = [10, 30];
const VALID_PALETTE_VARIANTS = ['LIGHT', 'DARK'];
const DEFAILT_PALETTE_VARIANT = VALID_PALETTE_VARIANTS[1];
const ARBUZ_SECRET = 'click-secret';

module.exports = {
  APPLICATION_NAME,
  ARBUZ_SECRET,
  DEFAULT_DELAYS,
  MAX_ENERGY_TO_CLICK,
  MIN_ENERGY_TO_CLICK,
  VALID_PALETTE_VARIANTS,
  DEFAILT_PALETTE_VARIANT,
};
